### ISSUE TITLE
grab any url which is buffering

### ISSUE THREAD

**Issue by icha1** [r3dbU7z/play-it-mpv#10]
Great work for someone who is learning! I was wondering if it is possible to somehow let the plugin grab any url which is buffering and pass it to mpv? Regardless of the sites supported. Maybe via the [Resource Timing API](https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API)?

**Comment by r3dbU7z** [comment]
Yeah, it's a working case. It's occurred to me, too. Indeed, sometimes the url on a web page can be plain text. I will look at your link and think about how to implement this feature. But I won't promise anything. Anyway, Thanks for the feedback.

**Comment by r3dbU7z** [comment]
H! @icha1, I added my own implementation of open text as link. Now, when you select the text in the context menu, the  "Play selecton with MPV"  item appears. Yes, it's not exactly what you wanted, but in my opinion it will be more convenient, because it does not require unnecessary actions. Please write your review if I did something wrong.
